In [3]:
import sys
sys.path.append('..')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
import pickle
import os

import xarray as xr
import xskillscore as xs

import torch

from utils.plotting_utils import show_metrics, from_torchtensor_to_xarray

In [4]:
# results_file_path = '../outputs/results_pde.pkl'
results_file_path = '../outputs/results_trained_models_2mT.pkl'
sample_metrics_file_path = metrics_file_path = '../pretrained_models/outputs/metrics_trained_models.pkl'
output_path = '../outputs/'

In [8]:
#load in model inference results dataframe (refer to notebooks/models_inference.ipynb for dataframe formatting)

results_df = pd.read_pickle(results_file_path)
metrics = pd.read_pickle(sample_metrics_file_path)

print(results_df)
# print(metrics)

for i in range (100):
    print(metrics.iloc[i])

   input_var target_var              model variable  \
0        all        2mT               ERA5      2mT
1        all        2mT               ERA5      2mT
2        all        2mT               ERA5      2mT
3        all        2mT               ERA5      2mT
4        all        2mT               ERA5      2mT
5        all        2mT          COSMO-CLM      2mT
6        all        2mT          COSMO-CLM      2mT
7        all        2mT          COSMO-CLM      2mT
8        all        2mT          COSMO-CLM      2mT
9        all        2mT          COSMO-CLM      2mT
10       all        2mT  Quadratic Interp.      2mT
11       all        2mT  Quadratic Interp.      2mT
12       all        2mT  Quadratic Interp.      2mT
13       all        2mT  Quadratic Interp.      2mT
14       all        2mT  Quadratic Interp.      2mT
15       all        2mT               UNET      2mT
16       all        2mT               UNET      2mT
17       all        2mT               UNET      2mT
18       all        2mT               UNET      2mT
19       all        2mT               UNET      2mT
20       all        2mT                GAN      2mT
21       all        2mT                GAN      2mT
22       all        2mT                GAN      2mT
23       all        2mT                GAN      2mT
24       all        2mT                GAN      2mT
25       all        2mT            LDM_res      2mT
26       all        2mT            LDM_res      2mT
27       all        2mT            LDM_res      2mT
28       all        2mT            LDM_res      2mT
29       all        2mT            LDM_res      2mT

                                           spat_distr         min         max  \
0   [[tensor(282.5619), tensor(282.5619), tensor(2...  272.312256  290.437225
1   [[tensor(273.5626), tensor(273.5626), tensor(2...  258.944519  289.312317
2   [[tensor(287.2497), tensor(287.2497), tensor(2...  281.060699  300.498718
3   [[tensor(289.4377), tensor(289.4377), tensor(2...  275.939758  301.378571
4   [[tensor(277.4988), tensor(277.4988), tensor(2...  269.379364  290.562653
5   [[tensor(284.8658), tensor(284.8658), tensor(2...  272.046997  291.097046
6   [[tensor(272.5653), tensor(272.5653), tensor(2...  258.345551  289.257843
7   [[tensor(289.1827), tensor(289.1827), tensor(2...  279.216433  300.745544
8   [[tensor(289.4932), tensor(289.4932), tensor(2...  272.379028  302.826691
9   [[tensor(276.9624), tensor(276.9624), tensor(2...  268.354431  290.773132
10  [[tensor(281.9189, dtype=torch.float64), tenso...  272.283768  290.436030
11  [[tensor(272.0475, dtype=torch.float64), tenso...  259.120345  289.316341
12  [[tensor(285.7877, dtype=torch.float64), tenso...  280.966308  300.497752
13  [[tensor(288.7735, dtype=torch.float64), tenso...  276.060706  301.350549
14  [[tensor(275.8469, dtype=torch.float64), tenso...  269.217826  290.576455
15  [[tensor(285.2124), tensor(285.1074), tensor(2...  272.151641  290.440552
16  [[tensor(274.2828), tensor(273.9750), tensor(2...  259.175036  289.461260
17  [[tensor(289.4093), tensor(289.2389), tensor(2...  279.179173  300.387674
18  [[tensor(289.3592), tensor(289.4838), tensor(2...  272.906145  302.222774
19  [[tensor(278.9632), tensor(278.7741), tensor(2...  268.592088  290.662524
20  [[tensor(285.2074), tensor(285.2103), tensor(2...  272.232208  290.584288
21  [[tensor(274.2933), tensor(273.3149), tensor(2...  258.907474  289.222410
22  [[tensor(288.7326), tensor(288.8675), tensor(2...  278.916580  300.495614
23  [[tensor(291.4054), tensor(291.3369), tensor(2...  272.572154  302.366057
24  [[tensor(278.3757), tensor(278.0760), tensor(2...  268.230961  290.573443
25  [[tensor(285.8373), tensor(285.3241), tensor(2...  271.948760  290.992424
26  [[tensor(272.7668), tensor(272.4056), tensor(2...  258.470093  289.707153
27  [[tensor(288.7050), tensor(287.9853), tensor(2...  279.196411  301.057229
28  [[tensor(291.1327), tensor(290.7827), tensor(2...  272.605147  302.413010
29  [[tensor(278.6646), tensor(278.4153), tensor(2...  268.111768  290.769008

             time_step
0  2014-04-24 02:00:00
1  2014-12-28 03:00:00
2  2019-09-02 02:00:00
3  2006-05-14 10:00:00
4  2016-05-02 04:00:00
5  2014-04-24 02:00:00
6  2014-12-28 03:00:00
7  2019-09-02 02:00:00
8  2006-05-14 10:00:00
9  2016-05-02 04:00:00
10 2014-04-24 02:00:00
11 2014-12-28 03:00:00
12 2019-09-02 02:00:00
13 2006-05-14 10:00:00
14 2016-05-02 04:00:00
15 2014-04-24 02:00:00
16 2014-12-28 03:00:00
17 2019-09-02 02:00:00
18 2006-05-14 10:00:00
19 2016-05-02 04:00:00
20 2014-04-24 02:00:00
21 2014-12-28 03:00:00
22 2019-09-02 02:00:00
23 2006-05-14 10:00:00
24 2016-05-02 04:00:00
25 2014-04-24 02:00:00
26 2014-12-28 03:00:00
27 2019-09-02 02:00:00
28 2006-05-14 10:00:00
29 2016-05-02 04:00:00
model         Quadratic Interp.
target_var                  2mT
var                         2mT
metric                     RMSE
value                  1.901043
Name: 0, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.516584
Name: 1, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.725706
Name: 2, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.615818
Name: 3, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                   0.21446
Name: 4, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.069683
Name: 5, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.760935
Name: 6, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.048485
Name: 7, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.642851
Name: 8, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.747683
Name: 9, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.496793
Name: 10, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.691005
Name: 11, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                   0.22102
Name: 12, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.568692
Name: 13, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.725367
Name: 14, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.482529
Name: 15, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.556308
Name: 16, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.647043
Name: 17, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.681585
Name: 18, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.143463
Name: 19, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.272758
Name: 20, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.681401
Name: 21, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.490969
Name: 22, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.646998
Name: 23, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.707805
Name: 24, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                   0.44258
Name: 25, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.435782
Name: 26, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.737275
Name: 27, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.667121
Name: 28, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.646493
Name: 29, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.636858
Name: 30, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.748606
Name: 31, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.572424
Name: 32, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.470678
Name: 33, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.340844
Name: 34, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.195412
Name: 35, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.773794
Name: 36, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.584235
Name: 37, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.371643
Name: 38, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.814499
Name: 39, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                   0.46617
Name: 40, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.553849
Name: 41, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                 -0.305539
Name: 42, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.651876
Name: 43, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.618424
Name: 44, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.557245
Name: 45, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.604638
Name: 46, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.643143
Name: 47, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.605191
Name: 48, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.679172
Name: 49, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.621861
Name: 50, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.408055
Name: 51, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         U10
metric                       R2
value                  0.557644
Name: 52, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.504598
Name: 53, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.688762
Name: 54, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.838283
Name: 55, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.205934
Name: 56, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                   0.62012
Name: 57, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.649118
Name: 58, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.684786
Name: 59, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.519436
Name: 60, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.485947
Name: 61, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.865189
Name: 62, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.653245
Name: 63, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.614955
Name: 64, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.528335
Name: 65, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.653789
Name: 66, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                 -0.045919
Name: 67, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.717111
Name: 68, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.289906
Name: 69, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.762411
Name: 70, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.694023
Name: 71, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                   0.66108
Name: 72, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.420385
Name: 73, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.632123
Name: 74, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.497175
Name: 75, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.476943
Name: 76, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.791818
Name: 77, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.341938
Name: 78, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                 -0.270562
Name: 79, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.505971
Name: 80, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.606392
Name: 81, dtype: object
model         Quadratic Interp.
target_var                   UV
var                         V10
metric                       R2
value                  0.691734